### PR TITLE
Joshua Clement- Assignment 3: SASS

### PR DESCRIPTION
**Pull request by joshuayclements**
@alohavolha @lusead 

Not sure if what i did is correct or even functioning properly but good luck and thanks in advance.

https://joshuayclements.github.io/assignments/

### CODE REVIEW

**Comment by alohavolha** [comment]
@joshuayclements Hey, Yosh! 
 there is a typo on line 7: should be @mixin, and now everything works properly :)

When you save a sass file, it should not give you an error "unable to compress the file" or something similar to this; also you usually should be able to see if your scss works when the proper variables, mixing, all the semantic highlighting should work ( that is one of the indicators that everything works properly)

**Comment by lusead** [comment]
Not sure if its just me but I cant see your sass file. Make sure your prepos is on and is tracking your working file. I guess Volha addressed this but yeah other wise code looks good!

**Comment by joshuayclements** [comment]
Thanks @alohavolha and @lusead I definitely forgot to open prepros while working on my file.

**Comment by joshuayclements** [comment]
@micjamking Final Submission

**Pull request closed without merging**
