### PR TITLE
MarkKamaura - Assignment 3: Sass

### PR DESCRIPTION
**Pull request by lusead**
@alohavolha  @joshuayclements @normaucore58 

Sorry so late guys but could u check my code? Thanks!

### CODE REVIEW

**Comment by joshuayclements** [comment]
http://lusead.github.io/assignments/

here is the URL @normaucore58 @alohavolha

**Comment by alohavolha** [comment]
Aloha, Mark! 

line 2: I don’t think you need “background-color” variable as you only use it once in your code. It also has a confusing name as you have multiple other background color properties but with different values. 

line: 8 I would move the body property after the mixing just for consistency for your code (keep all sass together and then the rest of the code)

you could also create a mixin: “columns-common-properties” and include such common values like { height, width, float } 

Aloha,
Volha

**Comment by alohavolha** [comment]
line 76: you can nest .columns in .info-01 :) 
line 84: same thing
line 92: same thing 
line 100: same thing :)

**Comment by alohavolha** [comment]
line 76: you can nest .info-01 in .info :) 
line 84: same thing
line 92: same thing 
line 100: same thing :)
I can't find your css values for the class .columns ... I am not sure if you even need that class. Is there a reason you use it in your html?

**Comment by joshuayclements** [comment]
So for your variables I'm not sure why you have a $header-height and $background-color? If it only appears once in your code and is not included in any mixins then I think you can just leave the value in the element.

Indent any nested items for readability, should look like html with elements getting tabbed in.

**Comment by lusead** [comment]
@alohavolha @joshuayclements  

Thanks guys!

**Comment by lusead** [comment]
@micjamking  Final Submission

**Pull request closed without merging**
