### PR TITLE
Sam Campos - Assignment 2: Basic HTML Page 

### PR DESCRIPTION
**Pull request by sam-campos**
@Ressa808 @githubhyelalee

### CODE REVIEW

**Comment by Ressa808** [comment]
looks all G

**Comment by sam-campos** [comment]
GOOD!

**Comment by githubhyelalee** [comment]
LOOKS ALL g.

**Comment by micjamking** [comment]
Hi @sam-campos 

Great job! There wasn't any mistakes, but just a couple of small modifications that could be made to make your code more DRY (see above).

-Mike

**Pull request closed without merging**
