### PR TITLE
Mayu Watanabe - Assignment 3: Sass

### PR DESCRIPTION
**Pull request by normaucore58**
@githubhyelalee @joshuayclements 

Could you check my work.
http://normaucore58.github.io/assignments/

Reference URL (Sass)
http://sass-lang.com/

### CODE REVIEW

**Comment by githubhyelalee** [comment]
Hi Mayu!

You forgot add `cf` to your html, in `main-info`.
You have mixin cf in your scss, so you can erase scss `line 133 to 141`.

**Comment by normaucore58** [comment]
Hi Hyela,

Thank you for checking. I fixed them.

**Comment by joshuayclements** [comment]
Hey Mayu so not sure if you did not indent nested items because you prefer it that way, but for readability it would make it easier if nested items for the main header and hero got indented. 

Also noticed you could create a variable for the hero-info height value if you choose since the 200px value appears 3 times. 

Rest of code looks good to me though.

**Comment by normaucore58** [comment]
Hi @joshuayclements 

That makes sense.
Thank you for checking.

**Comment by normaucore58** [comment]
@micjamking Final Submission

**Pull request closed without merging**
