### PR TITLE
Hyela Lee - Assignment 2:Creating layouts in HTML/CSS

### PR DESCRIPTION
**Pull request by githubhyelalee**
@normaucore58, @sam-campos 
note:1 Apple homepage had 3 sections that include Hero-slide, info-4columns, black quote. But they updated, now they have only hero section. 
note:2 I am not using absolute or relative positioning since I put header in container. But Mike demonstrated in differently in class, I think. 
Any thoughts or suggestion? 

If you think it's good to go, please comment, "Run Forest, Run"

### CODE REVIEW

**Comment by githubhyelalee** [comment]
@micjamking Final Submission

**Comment by sam-campos** [comment]
Run Forrest, Run!

**Comment by normaucore58** [comment]
Run Forest, Run.

**Comment by micjamking** [comment]
Hi @githubhyelalee 

Great job Hyela! Everything looks good, although we'll talk about the appropriate way to structure your grid so you work in percentages rather than hard pixel values this week.

-Mike

**Comment by githubhyelalee** [comment]
@micjamking Haha, Sorry! Mike! And, Please let me know later. I realized I can use point, like 33.3% rather than use pixels.
And I just remind that Chris Ota mentioned (I had asked him long time ago) that he using "px" than "%" or "em". And now I am wonder what were he meant for that.

**Comment by micjamking** [comment]
Hi @githubhyelalee, Chris Ota probably recommended pixels to you because it is the easiest to learn and master CSS with, not because it is the best to use in every case. For first year students in web design, I would also recommend designing in pixels instead of `em` and `%`, until you understand how floats work together with margin/padding (especially if you haven't learned `box-sizing: border-box` yet). 

Using `em` & `%` can require doing some sophisticated math at times, and generally planning ahead for how your layout and components will work together. Designing using `em` & `%` is much easier in Sass since you can do basic Math operations with it. Best practice for responsive web design is to create a fluid, percentage based grid, since that allows your layout and components to resize with the browser.

Ethan Marcotte, the designer who coined the term _Responsive Web Design_, has a great article on designing responsively using `em` and `%` values to create fluid layouts.
- [A List Apart: Fluid Grids](http://alistapart.com/article/fluidgrids) 

We'll be talking about this in class this week, but I just thought I would share with you since you are already there.

**Pull request closed without merging**
