### PR TITLE
Mayu Watanabe - Assignment 4: CSS Architecture

### PR DESCRIPTION
**Pull request by normaucore58**
I'm so sorry for late mention.
Could you check my works?
Thank you.

@lusead @joshuayclements

### CODE REVIEW

**Comment by normaucore58** [comment]
this is my link http://normaucore58.github.io/assignments/

**Comment by joshuayclements** [comment]
Hey Mayu, thanks for posting that link, was having trouble looking up your webpage.

So the architecture looks good, but I noticed that you have both a _reset.scss and a reset.css, I am pretty sure that since you have already transferred your reset into your base folder that you no longer need a reset.css. Other than that, I think you are good to go.

**Comment by lusead** [comment]
Code looks good. I didnt see the additional reset so you must have changed it. Good job!

**Comment by normaucore58** [comment]
Thank you for checking @joshuayclements :) but I couldn't find my "reset.css".

**Comment by normaucore58** [comment]
Thanks Mark!

**Comment by normaucore58** [comment]
@micjamking Final Submission

**Pull request closed without merging**
