### PR TITLE
myounghoon Kim Assignment 4: CSS Architecture

### PR DESCRIPTION
**Pull request by myoung0724**
@githubhyelalee @lusead @micjamking 
Please check my assignment, I'm not sure what's gone wrong.

http://myoung0724.github.io/assignments-1/

### CODE REVIEW

**Comment by lusead** [comment]
@myoung0724  Code looks good! Did not see anything alarming that you would have to change. Good Job!

**Comment by githubhyelalee** [comment]
Hi @myoung0724 

-You should call full request to ghpage, not to your master like below photo.(I think?)
screen shot 2015-09-28 at 5 54 59 pm

-It looks like you don't have anything except the header because you lost all height for all the other sections. See attachment photo below. Give the height each sections and it will show off back.
높이를 전부 지우신거같아요. 섹션들이랑 푸터 높이hegiht가 없어서 그러니까 다시 높이 쓰시면 살아날꺼에요. 아마 하시면서 다 지우신듯.
screen shot 2015-09-28 at 6 08 09 pm

-In `_utilities.scss`, line 3 to line 32 should go to `_header.scss` file. Their are not `Variables` they are `header`.

-You compressed your css file, so I can't look how it looks like in css file. Maybe leave the css file as `extract` is better.

-In your HTML,
<section class="site-info"> should be `<section class="site-info cf">` . 
cf is "clear" and you memeber what is clear for? :)  You need to include it on you HTML TOO. 
css안에만 쓰고 html에 없으면 있으나마나 한거겠죵? ^^

**Comment by lusead** [comment]
Sorry Myoung I did not see your browser view as I went to your personal profile. But Hylea offered awesome advice and I am sure she caught things that I did not see.

**Comment by myoung0724** [comment]
@micjamking Final Submission

**Pull request closed without merging**
