### PR TITLE
Hyela Lee - Assignment 3: Sass

### PR DESCRIPTION
**Pull request by githubhyelalee**
@alohavolha @Yeona 
https://githubhyelalee.github.io//assignments/
Please leave the message so I can have a good night.

### CODE REVIEW

**Comment by alohavolha** [comment]
Your code looks good, just a couple things:
line 87 and 92 the parenthesis are not necessary (specifically to this type of math operations). Still works either way though.
line 105: you could nest “columns:last-child:{margin-right:0;}” in “.columns" and use "&:last-child...”

**Comment by githubhyelalee** [comment]
@alohavolha Woo! Good points! Thanks Voliha! :)

**Comment by githubhyelalee** [comment]
@micjamking final submission. (I will fix pixel in later~~~)

**Comment by micjamking** [comment]
Great job Hyela! I left some comments on the specific commit (8e71d2102a08ed29ab9d48485d794e9e4275e38a).

I didn't count off for this, but make sure you are making your pull requests via the `gh-pages` branch.

-Mike

**Pull request closed without merging**
