### PR TITLE
Mayu Watanabe - Assignment 2: Creating layouts in HTML/CSS

### PR DESCRIPTION
**Pull request by normaucore58**
@alohavolha @myoung0724

### CODE REVIEW

**Comment by myoung0724** [comment]
nice!

**Comment by myoung0724** [comment]
good!

**Comment by normaucore58** [comment]
My site is "Sass".
http://sass-lang.com/

**Comment by normaucore58** [comment]
@lusead

**Comment by normaucore58** [comment]
@micjamking Final Submission

**Comment by micjamking** [comment]
Hi @normaucore58 

Overall, good job! While I didn't make a hard rule about your header needing to use relative/absolute positioning, you don't have any examples of it on your site and I'm concerned you may not understand how it works. See [my comment above](https://github.com/kcc-nma-art258/assignments/pull/34#commitcomment-13333655).

-Mike

**Pull request closed without merging**
