### PR TITLE
please get me groceries

### PR DESCRIPTION
**Pull request by joshuayclements**
@alohavolha, @githubhyelalee

### CODE REVIEW

**Comment by githubhyelalee** [comment]
Since you don't use any percentage, CSS line 5, might not necessary. 
html,
body {
  height: 100%;
}

Other than that, Looks good.

**Comment by alohavolha** [comment]
Good job! Looks like Apple website :) 
I would just extend the footer : make the height bigger.

**Comment by joshuayclements** [comment]
@micjamking

**Comment by githubhyelalee** [comment]
@joshuayclements I thought he meant put your name, not his name.
screen shot 2015-09-13 at 1 47 46 pm

**Comment by micjamking** [comment]
Hi @joshuayclements. Great job! I didn't count off for this, since I wasn't very clear in my in-class explanation, but just remember going forward to turn in your work following the `NMA Bot - Assignment #2: Basic HTML/CSS site` example.

**Pull request closed without merging**
