### PR TITLE
Mark Kamaura-Assignment 2: Basic HTML Page

### PR DESCRIPTION
**Pull request by lusead**
@alohavolha @joshuayclements

### CODE REVIEW

**Comment by joshuayclements** [comment]
Your code seems to be functioning fine, but it is hard to read your html since the tab-ins are not consistent throughout the document. 

For your CSS re-order your classes and elements so that they mirror the hierarchy in the HTML document.

**Comment by lusead** [comment]
@normaucore58

**Comment by lusead** [comment]
@joshuayclements Thanks Yosh, Ill look into that.

**Comment by normaucore58** [comment]
Looks there is no unless things in your html and css:) but organizing more as Yosh said, makes it easier for everyone to fix and understand later.

By the way, for each style in a css, placing them in the same order as each style is unnecessary? I like to do this way but I'm not sure.

**Comment by lusead** [comment]
@normaucore58 Thanks and I am not sure what is the best practice for organizing files.

**Comment by lusead** [comment]
@micjamking Final Submission

**Comment by lusead** [comment]
Final Submission

**Comment by alohavolha** [comment]
sorry I am late, but it looks good! 
:) :+1:

**Comment by micjamking** [comment]
Hi @lusead,

Overall, your HTML/CSS looks very good. You do have an unused element in your HTML; since you marked this as the Apple website wireframe, I'm assuming this should have been a section with 4 floated info sections inside of it (see below). If you make this change, I'll update your grade and you should be good to go.
- Mike

**Pull request closed without merging**
