### PR TITLE
Volha Douban—Assignment 4: CSS Architecture

### PR DESCRIPTION
**Pull request by alohavolha**
I hope everyone is having a great weekend so far :100: 
Please take a moment this lovely sunny warm Saturday to pull a chair underneath a palm tree and review my lovely code  @joshuayclements @lusead 
all suggestions highly appreciated :)
http://alohavolha.github.io/assignments  

p.s. I don't have a "pages" folder as in my code I simply don't have anything to put in there.

### CODE REVIEW

**Comment by joshuayclements** [comment]
So I am not seeing anything wrong with the way you set up your css architecture, and I agree that if you do not have a need for a pages folder at this time, that it's not necessary to include. 

On a different note, did you change your search-bar file to a main-nav file? I know there is nothing wrong with that, but good job thinking about how to implement a system that fits your needs with what we just learned. Should of thought of that too, but not as good as you I guess.

**Comment by alohavolha** [comment]
@joshuayclements  thanks Yosh! 
Yeah, I left out the search-bar because I don't have one.

**Comment by alohavolha** [comment]
@micjamking Final Submission

**Comment by lusead** [comment]
Ahh dont wanna wait for me? Sorry but code looks good.

**Comment by alohavolha** [comment]
My deep apologies sir @lusead ! Your comments are highly valuable:) just thought you got busy. 
I was afraid to forget to submit it by midnight ( but was still waiting for your review which I received—thank you).

**Pull request closed without merging**
