### PR TITLE
MarkKamaura Assignment 4 css architecture

### PR DESCRIPTION
**Pull request by lusead**
@normaucore58 @joshuayclements Sorry so late again but check my code onegaishimasu.

### CODE REVIEW

**Comment by lusead** [comment]
http://lusead.github.io/assignments/

**Comment by normaucore58** [comment]
Hi. Looks good Mark.

**Comment by joshuayclements** [comment]
So I don't think that you need the reset.css now that you have a _reset.scss. Also I noticed that you created a body module for what I assume is the body element. Did you consider throwing that into your grid instead? I mean I don't think there is a right or wrong way of defining your modules but just a thought.

**Comment by lusead** [comment]
Ahh thanks Yosh.

**Comment by lusead** [comment]
Thanks guys @normaucore58 @joshuayclements  

@micjamking  Final Submission

**Pull request closed without merging**
