### PR TITLE
Kalena De Lima - Assignment 4: CSS Architecture

### PR DESCRIPTION
**Pull request by kalenakudelima**
@alohavolha @githubhyelalee

### CODE REVIEW

**Comment by githubhyelalee** [comment]
Hi Kalena!
Good Job!

HTML,
1.You have a float, so you need cf(clear) in `<section class="info common-height">` section.
2. Since you don't use `wrapper` in your css, so erase `<div class="wrapper">`
3. Don't need to have two class name for header, section, main-footer. You could erase `common-height`class and give the height to header, section, and main-footer classes.

SCSS,
1. in html, `<section class="info common-height">` have double height. I would simply erase  in scss line 43: `.info { height: auto; }`
1. You're not using nesting. You could use header or info section for nesting. 
2. Volha told me I could use `&` for `.columns:first-child` :) (I guess any pseudo)

Oh, you could put website link like the below photo when you asking pull request.( I think you just did this quickly, so just for the next time) :)
screen shot 2015-09-22 at 9 56 47 pm

**Comment by alohavolha** [comment]
Hey Kalena :) 
Hyela brought up good points! 
to add to that:
You need to apply class “.cf” to your section “.info” in your HTML because you need to clear the float after the floating elements in the section. 
And in SCSS: for your " .info" add {@include cf} Currently in your code you do have @mixin cf ... but you are not applying it anywhere in the code. 
Also for nesting: try see whether there is anything you could nest in your code. For ex. you could nest your "info-01", ".info-02" and ".info-03" in your ".info".

**Comment by kalenakudelima** [comment]
@sam-campos @myoung0724

**Comment by sam-campos** [comment]
hey kalena, i think you just need a _ for home and utilities. I think?  other than that, :)

**Comment by myoung0724** [comment]
It looks good!

**Pull request closed without merging**
