### PR TITLE
Volha Douban—Assignment 3: Sass

### PR DESCRIPTION
**Pull request by alohavolha**
Happy Saturdays, fellas! @lusead  @joshuayclements @kalenakudelima 
If you get a moment some time this beautiful sunny Saturday, please review my code and let me know if there is anything I need to change in your opinion. 
Mucho appreciated :)

http://alohavolha.github.io/assignments

### CODE REVIEW

**Comment by joshuayclements** [comment]
Not sure if variable $site-info-width is necessary since it only appears twice in code, Mike's notes say that values that appear 3 or more times should be replaced by a variables. That is up to you though, but could you instead make the 60px height value of items found in header appear as a variable since it appears more than 3 times.

Also I think Mike said that all SASS code should appear before the main CSS (I think at least), so consider moving the body element below you Mixins.

Your nested section looks good, but you changed the spelling of the color gray  to "grey" for some of the values. Not sure if this is being recognized as a value since in America gray is spelt with an A as opposed to other parts of the world where it is spelt with an E. 

Hope this helped and sorry for the late response, pulling my hair out over here.

**Comment by lusead** [comment]
Sorry so late! But code looks good but you may want to consider separating the reset to another style sheet.(not sure if this is the right way but I did that and it helps to keep the css cleaner.) Also not entirely certain but you have on the main nav saying "$header-height - 30%" I dont know if this is right or wrong but I thought that operators (if that is what it is) has a parentheses? And lastly minor spelling errors like "height" being spelt "hight" Not a big deal as u referenced the right name in your code.  Overall good job!

**Comment by alohavolha** [comment]
Mucho appreciated master @joshuayclements !
the sass code goes before the main css but right after the reset so I think I will follow Mark's advice and move my reset into a different file. 
Also, I have no idea where you see the word "grey"—I do not have it in my code...maybe some rendering issue in the dev tools. 
Not sure what you mean by height value "60px" ? I only have height 60px once and the only one that repeats is 50px and I have a variable for that. Can you please be a little more specific? What lines?

**Comment by alohavolha** [comment]
@lusead thank you!
Yeah, good idea to separate the reset into a different file. 
also "height" is on autocorrect for Atom so I am guessing it offers both: the British and American way :)

**Comment by alohavolha** [comment]
@lusead  good points! thank you

**Comment by lusead** [comment]
No prob!

**Comment by alohavolha** [comment]
@micjamking  Final Submission

**Comment by alohavolha** [comment]
@micjamking  Final Submission

**Comment by micjamking** [comment]
Hi @alohavolha; Great job overall. I made some minor comments on the specific commit 5fa3e3623c665eb60e96df6fbbe06b7d362e2358.

I didn't count off for this, but make sure you are making your pull requests via the `gh-pages` branch.

-Mike

**Pull request closed without merging**
