### PR TITLE
Joshua Clements–Assignment 4: CSS Architecture

### PR DESCRIPTION
**Pull request by joshuayclements**
@alohavolha @lusead @normaucore58 

Sorry for the late request guys. Does anyone know if the reason some of my files (i.e _home.scss, _search-bar.scss) are not showing up due to there being no css in the files? Or should they show up regardless? 

https://joshuayclements.github.io/assignments/

### CODE REVIEW

**Comment by alohavolha** [comment]
The architecture looks good to me :+1: 

Just a couple things that I would consider  paying attention to:
1. You have _search-bar.scss but you didn't include your code in there, although you do have code for your search bar. Since this website is simple you could keep it that way, but when working on complex websites, try separating it. Currently it looks like your search-bar  ".main-search" is nested in your header—I would extract it and place it in the "_search-bar.scss" file.
2. I would also consider just deleting "_home.scss" and "_site-info.scss" since the files are blank.

I do not know the exact answer to your question, but would guess that Chrome Dev Tools doesn't show it  because like you said the files are empty.

**Comment by lusead** [comment]
Code looks good buddy

**Comment by joshuayclements** [comment]
Thanks @alohavolha @lusead. Those were my thoughts as well Volha, but I was think that I might as well just leave the files for now since eventually we will be inputting more html and css, although at the moment it is just wetting my code. As far as the search bar, I agree that taking it out of the nesting would make sense for the current layout that I have, but it would probably be better if I created a module for my main-nav like you. And thanks for getting back so quick. I think in the future it would probably be better if me and @lusead submitted our files days in advance rather then waiting till the last day as the HW is not that time consuming.

**Comment by joshuayclements** [comment]
@micjamking Final Submission

**Pull request closed without merging**
